#!/bin/sh

# Run in our user's home directory
export HOME=/home/syncthing
cd $HOME

# These directories should exist and be owned by the user
for DIR in repos .config/syncthing; do
    test -d $DIR || mkdir -p $DIR
    chown syncthing:syncthing $DIR
    chmod 0750 $DIR
done

# Actually kickoff the sync
# Note:
#   - We set the "don't restart" environment flag - whatever is monitoring this
#     container can handle that.
#   - We explicitly override the GUI address to bind on 0.0.0.0, since users of
#     the container itself can decide where/how they want to expose it.
#   - We tell Syncthing to not start a browser
exec su - syncthing -c 'STNORESTART=yes STGUIADDRESS="http://0.0.0.0:8080" /usr/local/bin/syncthing -no-browser'
