#!/bin/sh

# Note:
#   - We set the "don't restart" environment flag - whatever is monitoring this
#     container can handle that.
#   - We explicitly override the GUI address to bind on 0.0.0.0, since users of
#     the container itself can decide where/how they want to expose it.
#   - We tell Syncthing to not start a browser
export STNORESTART=yes
export STGUIADDRESS="http://0.0.0.0:8080"

exec /usr/local/bin/syncthing -no-browser
